# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Date
        id: date
        shell: pwsh
        run: Get-Date
 
      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          Invoke-Expression -Command ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Choco install googlechrome
        shell: pwsh
        run: choco install googlechrome -y

      - name: Download chromedriver
        shell: pwsh
        run: | 
          Start-BitsTransfer 'https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_win32.zip'
          Expand-Archive .\chromedriver_win32.zip
 
      - name: Install Module Selenium
        shell: pwsh
        run: | 
          Install-Module -Name Selenium -RequiredVersion 3.0.1 -Force
 
      - name: Update selenium assemblies
        shell: pwsh
        run: | 
          $PathSelenium = Get-Module Selenium -ListAvailable
          Copy-Item ".\chromedriver_win32\chromedriver.exe" -Destination "$($PathSelenium.ModuleBase)\assemblies" -Force
          
      - name: Test selenium Hellow World
        shell: pwsh
        run: | 
          $Driver = Start-SeChrome
          $URL = Enter-SeUrl https://www.mcafee.com/enterprise/en-us/downloads/my-products.html -Driver $Driver
          $URL
          Stop-SeDriver -Driver $Driver
    
    
    
